spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  flyway:
    locations: classpath:db/migration/h2
    enabled: true
  datasource:
    url: jdbc:h2:mem:persistence-bug-investigation;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    database: h2
    properties:
      hibernate:
        generate_statistics: false #Turn it on only when you need for analysing queries. Do not leave it on!
    show-sql: true #Turn it on only when you need for analysing queries. Do not leave it on!
    open-in-view: false #Do not allow Spring to automagically fetch data from database
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        type: WARN
